<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@rapidmotors.com',
            'password' => Hash::make('Admin123!'),
            'is_admin' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Oldtimer cars (5)
        $oldtimers = [
            [
                'name' => 'Chevelle SS',
                'manufacturer' => 'Chevrolet',
                'year' => 1970,
                'category' => 'oldtimer',
                'price' => 125000.00,
                'horsepower' => 450,
                'engine' => '7.4L V8 LS6',
                'top_speed' => 210.0,
                'acceleration' => 5.4,
                'description' => 'One of the most defining cars of the American muscle car era. Brutal power and an unmistakable silhouette.',
                'is_featured' => true,
            ],
            [
                'name' => '300SL Gullwing',
                'manufacturer' => 'Mercedes-Benz',
                'year' => 1955,
                'category' => 'oldtimer',
                'price' => 1200000.00,
                'horsepower' => 215,
                'engine' => '3.0L I6',
                'top_speed' => 260.0,
                'acceleration' => 8.8,
                'description' => 'An iconic sports car with gullwing doors. The supercar of the 1950s.',
                'is_featured' => false,
            ],
            [
                'name' => 'E-Type Series 1',
                'manufacturer' => 'Jaguar',
                'year' => 1961,
                'category' => 'oldtimer',
                'price' => 280000.00,
                'horsepower' => 265,
                'engine' => '3.8L I6',
                'top_speed' => 241.0,
                'acceleration' => 7.1,
                'description' => 'Enzo Ferrari called it the most beautiful car ever made. British elegance and performance in one.',
                'is_featured' => false,
            ],
            [
                'name' => '250 GTO',
                'manufacturer' => 'Ferrari',
                'year' => 1962,
                'category' => 'oldtimer',
                'price' => 48000000.00,
                'horsepower' => 300,
                'engine' => '3.0L V12',
                'top_speed' => 280.0,
                'acceleration' => 6.1,
                'description' => 'The most valuable car in the world. Only 36 units were ever built.',
                'is_featured' => false,
            ],
            [
                'name' => '911 Carrera RS 2.7',
                'manufacturer' => 'Porsche',
                'year' => 1973,
                'category' => 'oldtimer',
                'price' => 950000.00,
                'horsepower' => 210,
                'engine' => '2.7L Flat-6',
                'top_speed' => 245.0,
                'acceleration' => 5.8,
                'description' => 'Where the legend began. The first RS with its iconic ducktail spoiler and timeless design.',
                'is_featured' => false,
            ],
        ];

        // Supercars (15)
        $supercars = [
            [
                'name' => 'Chiron',
                'manufacturer' => 'Bugatti',
                'year' => 2021,
                'category' => 'supercar',
                'price' => 3000000.00,
                'horsepower' => 1500,
                'engine' => '8.0L W16 Quad-Turbo',
                'top_speed' => 420.0,
                'acceleration' => 2.4,
                'description' => 'The ultimate expression of the Bugatti hypercar. 1,500 horsepower, a quad-turbo W16 engine, and an electronically limited top speed of 420 km/h.',
                'is_featured' => false,
            ],
            [
                'name' => 'SF90 Stradale',
                'manufacturer' => 'Ferrari',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 625000.00,
                'horsepower' => 1000,
                'engine' => '4.0L V8 + 3 E-Motor',
                'top_speed' => 340.0,
                'acceleration' => 2.5,
                'description' => 'Ferrari\'s first plug-in hybrid supercar. 1,000 combined horsepower.',
                'is_featured' => true,
            ],
            [
                'name' => 'Aventador SVJ',
                'manufacturer' => 'Lamborghini',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 573000.00,
                'horsepower' => 770,
                'engine' => '6.5L V12',
                'top_speed' => 350.0,
                'acceleration' => 2.8,
                'description' => 'The farewell symphony of the naturally aspirated V12. A Nürburgring record holder.',
                'is_featured' => true,
            ],
            [
                'name' => '720S',
                'manufacturer' => 'McLaren',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 315000.00,
                'horsepower' => 720,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 341.0,
                'acceleration' => 2.9,
                'description' => 'The crown jewel of McLaren\'s Super Series. Breathtaking performance and design.',
                'is_featured' => false,
            ],
            [
                'name' => '918 Spyder',
                'manufacturer' => 'Porsche',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 1800000.00,
                'horsepower' => 887,
                'engine' => '4.6L V8 + 2 E-Motor',
                'top_speed' => 345.0,
                'acceleration' => 2.6,
                'description' => 'The German member of the Holy Trinity. A perfect symbiosis of electric and combustion power.',
                'is_featured' => false,
            ],
            [
                'name' => 'AMG One',
                'manufacturer' => 'Mercedes-AMG',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 2700000.00,
                'horsepower' => 1063,
                'engine' => '1.6L V6 Turbo Hybrid',
                'top_speed' => 352.0,
                'acceleration' => 2.9,
                'description' => 'An F1 engine on the road. Lewis Hamilton\'s technology in a road-legal machine.',
                'is_featured' => true,
            ],
            [
                'name' => 'Huayra BC',
                'manufacturer' => 'Pagani',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 3400000.00,
                'horsepower' => 800,
                'engine' => '6.0L V12 Twin-Turbo',
                'top_speed' => 370.0,
                'acceleration' => 2.8,
                'description' => 'Art on four wheels. A limited-edition masterpiece created in honour of Benny Caiola.',
                'is_featured' => false,
            ],
            [
                'name' => 'Gemera',
                'manufacturer' => 'Koenigsegg',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 1700000.00,
                'horsepower' => 1700,
                'engine' => '2.0L I3 + 3 E-Motor',
                'top_speed' => 400.0,
                'acceleration' => 1.9,
                'description' => 'The world\'s first four-seater mega-hypercar. A new definition of the family supercar.',
                'is_featured' => false,
            ],
            [
                'name' => 'Valkyrie',
                'manufacturer' => 'Aston Martin',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 3200000.00,
                'horsepower' => 1160,
                'engine' => '6.5L V12 Hybrid',
                'top_speed' => 402.0,
                'acceleration' => 2.5,
                'description' => 'A masterpiece by F1 engineer Adrian Newey. Blurring the line between wind tunnel and road.',
                'is_featured' => false,
            ],
            [
                'name' => 'GT2 RS',
                'manufacturer' => 'Porsche',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 347000.00,
                'horsepower' => 700,
                'engine' => '3.8L Flat-6 Twin-Turbo',
                'top_speed' => 340.0,
                'acceleration' => 2.7,
                'description' => 'The fastest road-legal 911 ever made. Nürburgring lap record holder.',
                'is_featured' => true,
            ],
            [
                'name' => 'Senna',
                'manufacturer' => 'McLaren',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 1100000.00,
                'horsepower' => 800,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 340.0,
                'acceleration' => 2.8,
                'description' => 'Created in memory of Ayrton Senna. Pure track car character with a road-legal licence plate.',
                'is_featured' => false,
            ],
            [
                'name' => 'Revuelto',
                'manufacturer' => 'Lamborghini',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 608000.00,
                'horsepower' => 1015,
                'engine' => '6.5L V12 + 3 E-Motor',
                'top_speed' => 350.0,
                'acceleration' => 2.5,
                'description' => 'Lamborghini\'s first V12 plug-in hybrid. The successor to the Aventador.',
                'is_featured' => false,
            ],
            [
                'name' => 'Jesko Absolut',
                'manufacturer' => 'Koenigsegg',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 3000000.00,
                'horsepower' => 1600,
                'engine' => '5.0L V8 Twin-Turbo',
                'top_speed' => 531.0,
                'acceleration' => 2.5,
                'description' => 'Koenigsegg\'s top-speed-optimised hypercar. Theoretical maximum: 531 km/h.',
                'is_featured' => false,
            ],
            [
                'name' => 'LaFerrari',
                'manufacturer' => 'Ferrari',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 3200000.00,
                'horsepower' => 963,
                'engine' => '6.3L V12 Hybrid',
                'top_speed' => 350.0,
                'acceleration' => 2.4,
                'description' => 'The Italian member of the Holy Trinity. Ferrari\'s first hybrid hypercar.',
                'is_featured' => false,
            ],
            [
                'name' => 'Venom F5',
                'manufacturer' => 'Hennessey',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 2100000.00,
                'horsepower' => 1817,
                'engine' => '6.6L V8 Twin-Turbo',
                'top_speed' => 484.0,
                'acceleration' => 2.6,
                'description' => 'An American hypercar with one goal: breaking the 500 km/h barrier.',
                'is_featured' => false,
            ],
        ];

        // Luxury cars (5)
        $luxuryCars = [
            [
                'name' => 'DBX707',
                'manufacturer' => 'Aston Martin',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 235000.00,
                'horsepower' => 707,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 310.0,
                'acceleration' => 3.3,
                'description' => 'The world\'s most powerful luxury SUV. British elegance meets brutal performance.',
                'is_featured' => false,
            ],
            [
                'name' => 'Speedtail',
                'manufacturer' => 'McLaren',
                'year' => 2023,
                'category' => 'luxury',
                'price' => 2250000.00,
                'horsepower' => 1070,
                'engine' => '4.0L V8 Hybrid',
                'top_speed' => 403.0,
                'acceleration' => 2.9,
                'description' => 'The spiritual successor to the McLaren F1. Central driving position, three seats.',
                'is_featured' => false,
            ],
            [
                'name' => 'Battista',
                'manufacturer' => 'Pininfarina',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 2200000.00,
                'horsepower' => 1900,
                'engine' => 'Quad Electric Motor',
                'top_speed' => 350.0,
                'acceleration' => 1.9,
                'description' => 'A fully electric hypercar with Italian design. 1,900 horsepower delivered in silence.',
                'is_featured' => false,
            ],
            [
                'name' => 'Urus Performante',
                'manufacturer' => 'Lamborghini',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 260000.00,
                'horsepower' => 666,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 306.0,
                'acceleration' => 3.3,
                'description' => 'A super SUV, Lamborghini style. Track car capabilities with a family-sized boot.',
                'is_featured' => false,
            ],
            [
                'name' => 'SLS AMG GT',
                'manufacturer' => 'Mercedes-Benz',
                'year' => 2013,
                'category' => 'luxury',
                'price' => 208000.00,
                'horsepower' => 583,
                'engine' => '6.2L V8',
                'top_speed' => 320.0,
                'acceleration' => 3.7,
                'description' => 'An iconic gullwing supercar with a thunderous V8 soundtrack and classic AMG character.',
                'is_featured' => true,
            ],
        ];

        // Insert cars (5 oldtimers + 15 supercars + 5 luxury cars = 25 total)
        foreach (array_merge($oldtimers, $supercars, $luxuryCars) as $car) {
            DB::table('cars')->insert(array_merge($car, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}